Repository kubesphere/devops-java-sample, pull requests merged in 2021-04, with the labels that each got.

#71 Add linuxsuren as a owner
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#66 Correct the wrong order number in the readme file
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#77 Provide an English version of the README file
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, lgtm, size/L
